# Generated by Django 2.2.7 on 2019-11-22 15:27

from django.contrib.postgres.operations import CITextExtension
import django.contrib.postgres.fields.citext
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(max_length=254, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('profile', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'active'), ('locked', 'locked'), ('disabled', 'disabled')], default='active', max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
