# Generated by Django 2.2.7 on 2019-11-22 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('issued', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('refresh', models.CharField(max_length=64, unique=True)),
                ('revoked', models.DateTimeField(null=True)),
                ('renewed', models.DateTimeField(null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tokens.Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
